'''Crie um sistema de cadastro de usuário que registre as informações de “nome, sexo, endereço, cidade, estado, CEP, telefone, data de nascimento, RG, nome do pai, nome da mãe e grau de escolaridade” do usuário.
O sistema deve exibir as informações do usuário em um texto amigável.'''

nome = input("digite o seu nome: ")
sexo = input("digite seu sexo: ")
endereço = input("digite o seu endereço: ")
cidade = input("digite sua cidade: ")
estado = input("digite o seu estado: ")
cep = input("digite seu cep: ")
telefone = input("digite seu telefone: ")
nascimento = input("digite sua data de nascimento: ")
rg = input("digite seu RG: ")
nomepai = input("digite o nome do seu pai: ")
nomemae = input("digite o nome da sua mãe: ")
grauescolar = input("digite seu grau de escolaridade: ")

print(f"nome: {nome}")
print(f"sexo: {sexo}")      
print(f"endereço: {endereço}")
print(f"cidade: {cidade}")
print(f"estado: {estado}")
print(f"cep: {cep}")
print(f"telefone: {telefone}")
print(f" data de nascimento: {nascimento}")
print(f"rg: {rg}")
print(f"nome do pai: {nomepai}")
print(f"nome da mae: {nomemae}")
print(f"grau escolar: {grauescolar}")
